# Generated by Django 4.0.5 on 2022-06-28 13:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsSummery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_url', models.CharField(max_length=200, null=True)),
                ('card_title', models.CharField(max_length=100, null=True)),
                ('summary_info', models.CharField(max_length=10000, null=True)),
                ('img_url', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TripNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_url', models.CharField(default='', max_length=200, unique=True)),
                ('title', models.CharField(default='', max_length=200)),
                ('loc', models.CharField(default='', max_length=100)),
                ('date', models.CharField(default='', max_length=10)),
                ('likeCnt', models.CharField(max_length=10, null=True)),
                ('shareCnt', models.CharField(max_length=10, null=True)),
                ('readCnt', models.CharField(max_length=10, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
